#!/usr/bin/env bash
set -euo pipefail

command -v brew >/dev/null 2>&1 || {
    echo "Homebrew is required: https://brew.sh" >&2
    exit 1
}

command -v xcodebuild >/dev/null 2>&1 || {
    echo "Install full Xcode from the App Store first." >&2
    exit 1
}

developer_dir="$(xcode-select -p)"
case "$developer_dir" in
    */Xcode.app/Contents/Developer) ;;
    *)
        echo "Select full Xcode before continuing:" >&2
        echo "  sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer" >&2
        exit 1
        ;;
esac

echo "Installing Homebrew build requirements..."
brew bundle --file="$(cd "$(dirname "$0")/.." && pwd)/Brewfile"

xcrun --sdk iphoneos --show-sdk-path >/dev/null
xcrun --sdk iphonesimulator --show-sdk-path >/dev/null

b2_path="$(brew --prefix boost-build)/bin/b2"
[[ -x "$b2_path" ]] || {
    echo "boost-build installed, but b2 is not executable at $b2_path" >&2
    exit 1
}

echo
echo "macOS requirements are ready."
echo "Homebrew b2: $b2_path"
echo "Boost 1.65 builds should use the bundled ./b2 generated by bootstrap.sh."
